name: Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install main dependencies
        run: npm install

      - name: Install renderer dependencies
        run: npm install --prefix src/renderer

      - name: Build & Publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run dist:publish
